# Attention! Migration ini hanya untuk model MutasiStok (legacy).
# Tidak digunakan aktif — bisa dilewati jika tidak diinginkan.


"""add mutasi_stok table v2

Revision ID: 8ac9387a76b6
Revises: e56a1b39e1f1
Create Date: 2025-05-29 05:44:07.915486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac9387a76b6'
down_revision = 'e56a1b39e1f1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutasi_stok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aksi', sa.String(length=10), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('harga_saat_mutasi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], name=op.f('fk_mutasi_stok_produk_id_produk')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_mutasi_stok_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mutasi_stok'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mutasi_stok')
    # ### end Alembic commands ###
