"""add mutasi_stok table

Revision ID: e56a1b39e1f1
Revises: 55450a643444
Create Date: 2025-05-29 05:37:13.735235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56a1b39e1f1'
down_revision = '55450a643444'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
