"""fix default timestamp kategori lastt

Revision ID: cff775d62e48
Revises: 86f15ccd089e
Create Date: 2025-05-26 23:56:32.239479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff775d62e48'
down_revision = '86f15ccd089e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
