"""restore lower index for kategori.nama

Revision ID: 0a2a0d23471e
Revises: 8ac9387a76b6
Create Date: 2025-05-29 09:24:21.118934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a2a0d23471e'
down_revision = '8ac9387a76b6'
branch_labels = None
depends_on = None

def upgrade():
    op.create_index(
        'kategori_nama_lower_idx',
        'kategori',
        [sa.text('lower(nama)')],
        unique=True
    )
    op.drop_table('mutasi_stok')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutasi_stok',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aksi', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('jumlah', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('harga_saat_mutasi', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('keterangan', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('waktu', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], name='fk_mutasi_stok_produk_id_produk'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_mutasi_stok_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_mutasi_stok')
    )
    # ### end Alembic commands ###
