"""fix log_aktivitas table

Revision ID: d336d07ba97e
Revises: 5898efee5860
Create Date: 2025-05-28 00:59:47.165415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd336d07ba97e'
down_revision = '5898efee5860'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_aktivitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.Column('aksi', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_aktivitas'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_aktivitas')
    # ### end Alembic commands ###
