"""add unique constraint to produk.nama

Revision ID: 7bc4198955dc
Revises: cff775d62e48
Create Date: 2025-05-27 02:17:30.929524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc4198955dc'
down_revision = 'cff775d62e48'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_produk_nama'), 'produk', ['nama'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_produk_nama'), 'produk', type_='unique')
    # ### end Alembic commands ###
