"""add harga_produk table

Revision ID: e2b2cf2dc990
Revises: 566f0f3356af
Create Date: 2025-05-27 23:32:26.563372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b2cf2dc990'
down_revision = '566f0f3356af'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harga_produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], name=op.f('fk_harga_produk_produk_id_produk')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harga_produk'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harga_produk')
    # ### end Alembic commands ###
