"""add log_aktivitas table

Revision ID: 5898efee5860
Revises: e2b2cf2dc990
Create Date: 2025-05-28 00:50:55.592993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5898efee5860'
down_revision = 'e2b2cf2dc990'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
