"""rollback update

Revision ID: 6a1670bc92d8
Revises: c5516c3a1008
Create Date: 2025-06-01 06:57:14.288501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1670bc92d8'
down_revision: Union[str, None] = 'c5516c3a1008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_log_aktivitas_user_id_user', 'log_aktivitas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_log_aktivitas_user_id_user'), 'log_aktivitas', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_log_aktivitas_user_id_user'), 'log_aktivitas', type_='foreignkey')
    op.create_foreign_key('fk_log_aktivitas_user_id_user', 'log_aktivitas', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
