"""initial schema

Revision ID: 2b854205dbcb
Revises: 
Create Date: 2025-05-29 10:36:37.981123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b854205dbcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_kategori_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kategori')),
    sa.UniqueConstraint('user_id', 'nama', name='uq_user_kategori_nama')
    )
    op.create_table('log_aktivitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waktu', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('aksi', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_log_aktivitas_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_aktivitas'))
    )
    op.create_table('produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('harga', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], name=op.f('fk_produk_kategori_id_kategori')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_produk_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produk')),
    sa.UniqueConstraint('user_id', 'nama', name='uq_user_produk_nama')
    )
    op.create_table('harga_produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], name=op.f('fk_harga_produk_produk_id_produk')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harga_produk'))
    )
    op.create_index('ix_harga_produk_produktgl', 'harga_produk', ['produk_id', sa.literal_column('tanggal DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_harga_produk_produktgl', table_name='harga_produk')
    op.drop_table('harga_produk')
    op.drop_table('produk')
    op.drop_table('log_aktivitas')
    op.drop_table('kategori')
    op.drop_table('user')
    # ### end Alembic commands ###
