"""update all table for each account part2

Revision ID: 55450a643444
Revises: 306962d40a89
Create Date: 2025-05-29 03:08:19.406770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55450a643444'
down_revision = '306962d40a89'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
