"""update all table for each account

Revision ID: 306962d40a89
Revises: c7cb00658485
Create Date: 2025-05-29 02:11:16.785161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '306962d40a89'
down_revision = 'c7cb00658485'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_harga_produk_produktgl', 'harga_produk', ['produk_id', sa.literal_column('tanggal DESC')], unique=False)
    op.add_column('kategori', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('kategori_nama_lower_idx', table_name='kategori')
    op.drop_constraint('uq_kategori_nama', 'kategori', type_='unique')
    op.create_unique_constraint('uq_user_kategori_nama', 'kategori', ['user_id', 'nama'])
    op.create_foreign_key(op.f('fk_kategori_user_id_user'), 'kategori', 'user', ['user_id'], ['id'])
    op.add_column('log_aktivitas', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('log_aktivitas', 'waktu',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(op.f('fk_log_aktivitas_user_id_user'), 'log_aktivitas', 'user', ['user_id'], ['id'])
    op.add_column('produk', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('produk_nama_lower_idx', table_name='produk')
    op.drop_constraint('uq_produk_nama', 'produk', type_='unique')
    op.create_unique_constraint('uq_user_produk_nama', 'produk', ['user_id', 'nama'])
    op.create_foreign_key(op.f('fk_produk_user_id_user'), 'produk', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_produk_user_id_user'), 'produk', type_='foreignkey')
    op.drop_constraint('uq_user_produk_nama', 'produk', type_='unique')
    op.create_unique_constraint('uq_produk_nama', 'produk', ['nama'], postgresql_nulls_not_distinct=False)
    op.create_index('produk_nama_lower_idx', 'produk', [sa.literal_column('lower(nama::text)')], unique=True)
    op.drop_column('produk', 'user_id')
    op.drop_constraint(op.f('fk_log_aktivitas_user_id_user'), 'log_aktivitas', type_='foreignkey')
    op.alter_column('log_aktivitas', 'waktu',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('log_aktivitas', 'user_id')
    op.drop_constraint(op.f('fk_kategori_user_id_user'), 'kategori', type_='foreignkey')
    op.drop_constraint('uq_user_kategori_nama', 'kategori', type_='unique')
    op.create_unique_constraint('uq_kategori_nama', 'kategori', ['nama'], postgresql_nulls_not_distinct=False)
    op.create_index('kategori_nama_lower_idx', 'kategori', [sa.literal_column('lower(nama::text)')], unique=True)
    op.drop_column('kategori', 'user_id')
    op.drop_index('ix_harga_produk_produktgl', table_name='harga_produk')
    # ### end Alembic commands ###
